#!/usr/bin/env tsx
/**
 * One-off backfill: write ~/serverResources.md for every existing user who
 * doesn't have one yet. Run as root (or with NOPASSWD sudo):
 *
 *   sudo tsx worker/scripts/backfill-server-resources.ts
 */

import 'dotenv/config';
import pg from 'pg';
import { exec } from 'child_process';
import { promisify } from 'util';
import { writeFile, access } from 'fs/promises';
import { constants } from 'fs';

const execPromise = promisify(exec);

const client = new pg.Client({
  user:     process.env.DB_USER,
  host:     process.env.DB_HOST ?? 'localhost',
  database: process.env.DB_NAME,
  password: process.env.DB_PASSWORD,
  port:     parseInt(process.env.DB_PORT ?? '5432'),
});

const masterDomain = process.env.MASTER_DOMAIN ?? '';
const smtpHost     = process.env.SMTP_HOST ?? `mail.${masterDomain}`;

const fmtMd   = (v: number | null | undefined) => (v === -1 || v == null) ? '∞ Unlimited' : String(v);
const fmtBool = (v: boolean | null | undefined) => v ? 'Yes' : 'No';

async function buildMd(username: string, limits: Record<string, any> | null): Promise<string> {
  const dbName = `${username}_db`;
  const dbUser = dbName;

  const nodever = await execPromise('node --version').then(r => r.stdout.trim()).catch(() => 'unavailable');
  const pyver   = await execPromise('python3 --version').then(r => r.stdout.trim()).catch(() => 'unavailable');
  let phpver = '8.3';
  try {
    const { stdout } = await execPromise('ls /etc/php/ 2>/dev/null | sort -V | tail -1');
    const detected = stdout.trim();
    if (detected && /^[78]\.\d{1,2}$/.test(detected)) phpver = detected;
  } catch { /* keep default */ }

  const diskDisplay = (limits?.disk_limit_mb != null && limits.disk_limit_mb !== -1)
    ? `${(limits.disk_limit_mb / 1024).toFixed(1)} GB`
    : '∞ Unlimited';
  const bwDisplay = (limits?.bandwidth_limit_mb != null && limits.bandwidth_limit_mb !== -1)
    ? `${(limits.bandwidth_limit_mb / 1024).toFixed(0)} GB`
    : '∞ Unlimited';

  return `# Server Resources

Welcome to your hosting account, **${username}**!
Below is everything you need to build and deploy custom web applications on this server.

---

## Your Plan Limits

| Resource          | Limit                          |
|-------------------|-------------------------------|
| Disk Storage      | ${diskDisplay}                 |
| Bandwidth         | ${bwDisplay}/month             |
| Domains           | ${fmtMd(limits?.domains_allowed)}  |
| Email Accounts    | ${fmtMd(limits?.email_accounts)}   |
| Databases         | ${fmtMd(limits?.databases_allowed)}|
| FTP Accounts      | ${fmtMd(limits?.ftp_accounts)}     |
| Cron Jobs         | ${fmtMd(limits?.cron_jobs)}        |
| SSH Access        | ${fmtBool(limits?.ssh_access)}     |
| Node.js Support   | ${fmtBool(limits?.nodejs_support)} |
| Python Support    | ${fmtBool(limits?.python_support)} |

---

## Runtimes

| Runtime   | Version        | Notes                          |
|-----------|---------------|--------------------------------|
| Node.js   | ${nodever}     | PM2-managed, auto-restart      |
| Python 3  | ${pyver}       | PM2-managed, auto-restart      |
| PHP       | ${phpver}      | PHP-FPM, per-domain config     |

---

## Your Database (MariaDB)

| Setting | Value       |
|---------|-------------|
| Host    | \`localhost\` |
| Port    | \`3306\`      |
| Name    | \`${dbName}\` |
| User    | \`${dbUser}\` |
| Pass    | *(see \`.env\`)* |

Credentials are in \`~/.env\`. Never commit that file to git.

---

## Deploying a Custom App

1. Upload your app files to \`~/public_html/<yourdomain>/\`
2. In the **Application Manager** → **Custom Runtimes**, click **New Application**
3. Pick your domain, runtime, and startup script
4. The server assigns you a port and proxies your domain to it automatically

Your app will survive reboots — PM2 saves its state after every start/stop.

---

## Mail / SMTP (Outbound)

| Setting       | Value                |
|--------------|----------------------|
| SMTP Host     | \`${smtpHost}\`      |
| SMTP Port     | \`587\` (STARTTLS)   |
| Auth          | Your email credentials |

---

## Available Services

| Service      | Access              |
|-------------|---------------------|
| MariaDB      | \`localhost:3306\`  |
| PHP-FPM      | Unix socket (nginx handles this automatically) |
| Mail (IMAP)  | \`${smtpHost}:993\` (SSL) |
| DNS          | Managed via the dashboard |
| SSL / HTTPS  | Automatic via Let's Encrypt on domain provisioning |

---

*Generated by Superhost · ${new Date().toUTCString()}*
`;
}

async function main() {
  await client.connect();

  const { rows: users } = await client.query<{
    username: string;
    disk_limit_mb: number | null;
    bandwidth_limit_mb: number | null;
    domains_allowed: number | null;
    email_accounts: number | null;
    databases_allowed: number | null;
    ftp_accounts: number | null;
    cron_jobs: number | null;
    ssh_access: boolean | null;
    nodejs_support: boolean | null;
    python_support: boolean | null;
  }>(`
    SELECT u.username,
           COALESCE(p.disk_quota_mb,       u.disk_limit_mb)        AS disk_limit_mb,
           COALESCE(p.bandwidth_gb * 1024, u.bandwidth_limit_mb)   AS bandwidth_limit_mb,
           p.domains_allowed, p.email_accounts, p.databases_allowed,
           p.ftp_accounts,    p.cron_jobs,      p.ssh_access,
           p.nodejs_support,  p.python_support
      FROM users u
      LEFT JOIN products p ON p.id = u.package_id
     ORDER BY u.username
  `);

  await client.end();

  let skipped = 0, written = 0, missing = 0;

  for (const user of users) {
    const { username, ...limits } = user;
    const homeDir = `/home/${username}`;
    const mdPath  = `${homeDir}/serverResources.md`;

    // Skip if home dir doesn't exist (system users, etc.)
    try {
      await access(homeDir, constants.F_OK);
    } catch {
      console.log(`  skip  ${username}  (no home dir)`);
      missing++;
      continue;
    }

    // Skip if file already exists
    try {
      await access(mdPath, constants.F_OK);
      console.log(`  ok    ${username}  (already has serverResources.md)`);
      skipped++;
      continue;
    } catch { /* file absent — write it */ }

    const content = await buildMd(username, limits);
    const tmp = `/tmp/serverResources_${username}.md`;
    await writeFile(tmp, content);
    await execPromise(`mv ${tmp} ${mdPath}`);
    await execPromise(`chown ${username}:${username} ${mdPath}`);
    console.log(`  wrote ${username}  → ${mdPath}`);
    written++;
  }

  console.log(`\nDone. written=${written}  skipped=${skipped}  no-home=${missing}`);
}

main().catch(err => { console.error(err); process.exit(1); });
