location /webmail {
    alias /var/www/roundcube;
    index index.php index.html;

    location ~ ^/webmail/(.+\.php)$ {
        alias /var/www/roundcube/$1;
        fastcgi_pass unix:/var/run/php/php8.5-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $request_filename;
        include fastcgi_params;
    }

    location ~* ^/webmail/(.+\.(jpg|jpeg|gif|css|png|js|ico|html|xml|txt))$ {
        alias /var/www/roundcube/$1;
    }

    location ~ ^/webmail/(bin|config|installer|logs|SQL|temp) {
        deny all;
    }
}
