-- Migration 022: self-service password setup tokens.
-- Lets migrated users (who have no dashboard/panel password) set one via a
-- single-use, expiring link generated by an admin. Tokens are stored hashed.
-- Apply after 021_full_featured.sql.

CREATE TABLE IF NOT EXISTS password_setup_tokens (
  id          BIGSERIAL   PRIMARY KEY,
  user_id     INTEGER     NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash  TEXT        NOT NULL,            -- sha256 of the raw token; raw is never stored
  expires_at  TIMESTAMPTZ NOT NULL,
  used_at     TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_password_setup_tokens_hash ON password_setup_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_password_setup_tokens_user ON password_setup_tokens(user_id);
